#server
#  servlet
#    context-path=/

server:  servlet:    context-path: /
  port: 8080
  


#spring:
#  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: net.sf.log4jdbc.DriverSpy
#    url: jdbc:log4jdbc:hsqldb:hsql://localhost:9001/testdb
#    username: sa  # username 정보 (원하는 것으로 입력)
#    password:  #password 정보 (원하는 것으로 입력)
#  ## JPA Setting Info
#  jpa:
#    hibernate:
#      ddl-auto: create  # option type: create, create-drop, update, validate, none
#    properties:
#      hibernate:
#        diarect: org.hibernate.dialect.HSQLDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
#        show_sql: true  # sql 쿼리를 보여줍니다.
#        format_sql: true  # sql query formatting
#        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.